apiVersion: v1
kind: Service
metadata:
  name: snail-job
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  - port: 1788
    targetPort: 1788
    nodePort: 31788
    name: grpc
  selector:
    app: snail-job
