apiVersion: v1
kind: Service
metadata:
  name: greptime
  labels:
    app: greptime
spec:
  selector:
    app: greptime
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    nodePort: 4000
  - name: rpc
    port: 4001
    targetPort: 4001
    nodePort: 4001
  - name: mysql
    port: 4002
    targetPort: 4002
    nodePort: 4002
  - name: postgres
    port: 4003
    targetPort: 4003
    nodePort: 4003
  type: NodePort